version: 2

models:
  - name: fct_orders
    description: "Fact table: orders enriched with users, products, promotions; revenue and retention metrics."
    meta:
      lightdash:
        metrics:
          unique_customers:
            type: count_distinct
            sql: "user_id"
            label: "Unique Customers"
        dimensions:
          - order_date
          - order_year
          - user_country
          - status
          - user_id
          - product_category
          - promo_code
    columns:
      - name: order_id
        description: "Order primary key."
        config:
          meta:
            dimension:
              type: number
      - name: user_id
        description: "Customer ID."
        config:
          meta:
            dimension:
              type: number
      - name: product_id
        config:
          meta:
            dimension:
              type: number
      - name: quantity
        config:
          meta:
            dimension:
              type: number
      - name: amount
        description: "Order amount (before promo)."
        config:
          meta:
            dimension:
              type: number
            metrics:
              total_revenue:
                type: sum
                format: usd
                label: "Total Revenue"
      - name: amount_after_promo
        description: "Order amount after promo discount."
        config:
          meta:
            dimension:
              type: number
            metrics:
              total_revenue_after_promo:
                type: sum
                format: usd
                label: "Revenue (after promo)"
      - name: order_date
        config:
          meta:
            dimension:
              type: timestamp
      - name: order_year
        config:
          meta:
            dimension:
              type: number
      - name: status
        config:
          meta:
            dimension:
              type: string
      - name: promo_id
        config:
          meta:
            dimension:
              type: number
      - name: user_email
        config:
          meta:
            dimension:
              type: string
      - name: user_country
        config:
          meta:
            dimension:
              type: string
      - name: product_name
        config:
          meta:
            dimension:
              type: string
      - name: product_category
        config:
          meta:
            dimension:
              type: string
      - name: product_price
        config:
          meta:
            dimension:
              type: number
      - name: promo_code
        config:
          meta:
            dimension:
              type: string
      - name: promo_discount_pct
        config:
          meta:
            dimension:
              type: number

  - name: dim_products
    description: "Dimension: products with cleaned category and has_price flag."
    columns:
      - name: product_id
        tests: [ unique, not_null ]
      - name: name
      - name: category
      - name: price
      - name: has_price
