version: 2

models:
  - name: fct_orders
    description: "Fact table: orders joined to users and products for revenue and
      retention metrics."
    meta:
      lightdash:
        metrics:
          unique_customers:
            type: count_distinct
            sql: "user_id"
            label: "Unique Customers"
        dimensions:
          - order_date
          - order_year
          - user_country
          - status
          - user_id
    columns:
      - name: order_id
        description: "Order primary key."
        config:
          meta:
            dimension:
              type: number
      - name: user_id
        description: "Customer ID."
        config:
          meta:
            dimension:
              type: number
      - name: amount
        description: "Order amount."
        config:
          meta:
            dimension:
              type: number
            metrics:
              total_revenue:
                type: sum
                format: usd
                label: "Total Revenue"
      - name: order_date
        description: "Order timestamp."
        config:
          meta:
            dimension:
              type: timestamp
      - name: order_year
        description: "Year of order (for grouping by year)."
        config:
          meta:
            dimension:
              type: number
      - name: product_id
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: quantity
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: status
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: user_email
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: user_country
        description: ""
        config:
          meta:
            dimension:
              type: string
