version: 2

models:
  - name: stg_orders
    description: "Staging orders: cleaned duplicates, nulls, dates as timestamp."
    columns:
      - name: order_id
        description: "Primary key."
        tests: [ unique, not_null ]
        config:
          meta:
            dimension:
              type: number
      - name: user_id
        description: "FK to users."
        config:
          meta:
            dimension:
              type: number
      - name: product_id
        description: "FK to products."
        config:
          meta:
            dimension:
              type: number
      - name: order_date
        description: "Order timestamp."
        config:
          meta:
            dimension:
              type: timestamp
      - name: quantity
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: amount
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: status
        description: ""
        config:
          meta:
            dimension:
              type: string

  - name: stg_users
    description: "Staging users: cleaned duplicates, standardized is_active."
    columns:
      - name: user_id
        description: "Primary key."
        tests: [ unique, not_null ]
        config:
          meta:
            dimension:
              type: number
      - name: email
        description: "User email."
        config:
          meta:
            dimension:
              type: string
      - name: created_at
        description: "Registration timestamp."
        config:
          meta:
            dimension:
              type: timestamp
      - name: name
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: country
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: is_active
        description: ""
        config:
          meta:
            dimension:
              type: boolean
