version: 2

models:
  - name: stg_orders
    description: "Staging orders: упрощённая подготовка без полного клининга."
    columns:
      - name: order_id
        description: "Primary key."
        tests: [ unique, not_null ]
        config:
          meta:
            dimension:
              type: number
      - name: user_id
        description: "FK to users."
        tests:
          - relationships:
              to: ref('stg_users')
              field: user_id
        config:
          meta:
            dimension:
              type: number
      - name: order_date
        description: "Order timestamp."
        config:
          meta:
            dimension:
              type: timestamp
      - name: quantity
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: amount
        description: ""
        config:
          meta:
            dimension:
              type: number
      - name: status
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: promo_id
        description: "Промокод (может быть пустым)."

  - name: stg_users
    description: "Staging users: лёгкая нормализация без полного клининга."
    columns:
      - name: user_id
        description: "Primary key."
        tests: [ unique, not_null ]
        config:
          meta:
            dimension:
              type: number
      - name: email
        description: "User email."
        config:
          meta:
            dimension:
              type: string
      - name: created_at
        description: "Дата регистрации (может быть в строковом формате)."
        config:
          meta:
            dimension:
              type: timestamp
      - name: name
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: country
        description: ""
        config:
          meta:
            dimension:
              type: string
      - name: is_active
        description: ""
        config:
          meta:
            dimension:
              type: boolean
